project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - slides.qmd   
    - live_sessions.qmd 
      
website:
  title: ""
  search: false

  navbar:
    title: BUSI 722-901
    file: index.qmd
    link-external-newwindow: true
    search: false
    right:   

      - text: Notebooks
        href: https://github.com/kerryback/2023-722-901-binder

      - text: Slides
        file: slides.qmd

      - text: Solutions 
        href: https://github.com/kerryback/busi722-901/tree/main/solutions

      - text: Live Session Recordings
        file: live_sessions.qmd

    

format:
  html:
    theme:
      light: flatly
      dark: superhero
    link-external-newwindow: true
      



