project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - slides.qmd   
    - live_sessions.qmd 
      
website:
  title: ""
  search: false

  navbar:
    title: BUSI 722-901
    file: index.qmd
    link-external-newwindow: true
    search: false
    right:   

      - text: Code Binder
        href: https://mybinder.org/v2/gh/kerryback/2023-722-901-binder.git/HEAD

      - text: Notebook Repo
        href: https://github.com/kerryback/2023-722-901-binder

      - text: Slide Decks
        file: slides.qmd

      - text: Live Session Recordings
        file: live_sessions.qmd

    

format: 
  html:
    theme: yeti
    scss: styles.css
    link-external-newwindow: true
      



